apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-job
  annotations:
    "helm.sh/hook": post-install, post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    metadata:
      name: {{ .Release.Name }}-job
    spec:
      restartPolicy: Never
      initContainers:
        - name: check-db-ready
          image: postgres:16.3-alpine3.20
          command: [ 'sh', '-c',
            'until pg_isready -h postgres -p 5432;
             do echo waiting for database; sleep 10; done;' ]
      containers:
        - name: migration
          image: pombnk/kuberrest-migrations:v2.0
          imagePullPolicy: {{ .Values.deployments.imagePullPolicy }}
