apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  #namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      - job_name: 'kuberrest-service'
        static_configs:
        - targets: [{{.Release.Name}}-service:80]
      - job_name: 'kuberrest-deploy'
        static_configs:
          - targets: [{{.Release.Name}}-deployment:80 ]